package com.chrynan.instantanswer.fields

object MetaFields {

    const val BLOCK_GROUP = "blockgroup"
    const val SOURCE_ID = "src_id"
    const val STATUS = "status"
    const val DESIGNER = "designer"
    const val DESCRIPTION = "description"
    const val LIVE_DATE = "live_date"
    const val IS_STACK_EXCHANGE = "is_stackexchange"
    const val SOURCE_DOMAIN = "src_domain"
    const val TAB = "tab"
    const val SOURCE_URL = "src_url"
    const val UNSAFE = "unsafe"
    const val PERL_MODULE = "perl_module"
    const val CREATED_DATE = "created_date"
    const val PRODUCTION_STATE = "production_state"
    const val EXAMPLE_QUERY = "example_query"
    const val PRODUCER = "producer"
    const val SOURCE_NAME = "src_name"
    const val DEV_DATE = "dev_date"
    const val REPO = "repo"
    const val NAME = "name"
    const val JS_CALLBACK_NAME = "js_callback_name"
    const val ID = "id"
    const val ATTRIBUTION = "attribution"
    const val DEV_MILESTONE = "dev_milestone"
    const val SIGNAL_FROM = "signal_from"
    const val TOPICS = "topic"
    const val DEVELOPERS = "developer"
    const val MAINTAINER = "maintainer"
    const val SOURCE_OPTIONS = "src_options"
}